change: add 'clean' to mvn cmd in tools/updateSlipStreamRepos script

diff --git a/tools/updateSlipStreamRepos b/tools/updateSlipStreamRepos
--- a/tools/updateSlipStreamRepos
+++ b/tools/updateSlipStreamRepos
@@ -101,7 +101,7 @@ install_project(){
   if [ -d ${1} ]
   then
     pecho "  - Installing ${1}... "
-    (cd ${1}; git_branch; if mvn install -DskipModules=true -Dmaven.test.skip=$SKIP_TESTS; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || MVN_INSTALL_HAD_ERROR="true";
+    (cd ${1}; git_branch; if mvn clean install -DskipModules=true -Dmaven.test.skip=$SKIP_TESTS; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || MVN_INSTALL_HAD_ERROR="true";
   else
     pecholn "  - Project ${1} not found. Skipping."
   fi
@@ -131,7 +131,7 @@ if $BUILD_SEPARATE_MODULES; then
     install_project $repo
   done
 else
-  (cd SlipStream && mvn install -Dmaven.test.skip=$SKIP_TESTS 1>&3 2>&4;)
+  (cd SlipStream && mvn clean install -Dmaven.test.skip=$SKIP_TESTS 1>&3 2>&4;)
 fi
 
 if $MVN_INSTALL_HAD_ERROR
