change: take into account new 'skipModules' property

diff --git a/tools/updateSlipStreamRepos b/tools/updateSlipStreamRepos
--- a/tools/updateSlipStreamRepos
+++ b/tools/updateSlipStreamRepos
@@ -38,6 +38,7 @@ REPOS+=("SlipStreamClient")
 REPOS+=("SlipStreamConnectors")
 
 exec 3>&1
+exec 4>&2
 
 pecho() {
   echo -n "${1}" 1>&3
@@ -47,11 +48,31 @@ pecholn() {
   echo "${1}" 1>&3
 }
 
-if [ "${1}" != "-v" ]
+VERBOSE="false"
+if [ "${1}" == "-v" ]
+then
+  VERBOSE="true"
+  shift
+fi
+
+BUILD_SEPARATE_MODULES="false"
+if [ "${1}" == "--separate-modules" ]; then
+  BUILD_SEPARATE_MODULES="true"
+  shift
+fi
+
+if [ "${1}" != "" ]; then
+  echo "$(basename $0): invalid option: ${1}."
+  echo "$(basename $0): only -v and --separate-modules are valid."
+  exit 1
+fi
+
+if ! $VERBOSE
 then
   exec 1>/dev/null
   exec 2>/dev/null
 fi
+
 
 if [ "${1}" == "-q" ]
 then
@@ -80,7 +101,7 @@ install_project(){
   if [ -d ${1} ]
   then
     pecho "  - Installing ${1}... "
-    (cd ${1}; git_branch; if mvn install -Dmaven.test.skip=$SKIP_TESTS; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || MVN_INSTALL_HAD_ERROR="true";
+    (cd ${1}; git_branch; if mvn install -DskipModules=true -Dmaven.test.skip=$SKIP_TESTS; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || MVN_INSTALL_HAD_ERROR="true";
   else
     pecholn "  - Project ${1} not found. Skipping."
   fi
@@ -104,10 +125,14 @@ fi
 pecholn
 pecholn "Installing projects:"
 
-for repo in "${REPOS[@]}"
-do
-  install_project $repo
-done
+if $BUILD_SEPARATE_MODULES; then
+  for repo in "${REPOS[@]}"
+  do
+    install_project $repo
+  done
+else
+  (cd SlipStream && mvn install -Dmaven.test.skip=$SKIP_TESTS 1>&3 2>&4;)
+fi
 
 if $MVN_INSTALL_HAD_ERROR
 then
