change: do 'git gc --auto' after 'git pull' for each repo

diff --git a/tools/updateSlipStreamRepos b/tools/updateSlipStreamRepos
--- a/tools/updateSlipStreamRepos
+++ b/tools/updateSlipStreamRepos
@@ -69,7 +69,7 @@ update_ss_repo(){
   if [ -d ${1} ]
   then
     pecho "  - Updating ${1}... "
-    (cd ${1}; git_branch; if git pull; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || GIT_PULL_HAD_ERROR="true";
+    (cd ${1}; git_branch; if git pull && git gc --auto; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || GIT_PULL_HAD_ERROR="true";
   else
     pecho "  - Repo ${1} is not yet cloned here. Cloning ${1}... "
     git clone git@github.com:slipstream/${1}.git && pecholn "$OK" || pecholn "$ERROR"
