change: add debug info in update-all script

diff --git a/tools/updateSlipStreamRepos b/tools/updateSlipStreamRepos
--- a/tools/updateSlipStreamRepos
+++ b/tools/updateSlipStreamRepos
@@ -20,12 +20,14 @@
 #     simple version of the script only one of -v or -q can be used at
 #     the same time.
 
+# Required for the pylint execution in project SlipStreamClient
 export LC_CTYPE="en_US.UTF-8"
 
 OK="$(tput setaf 2) OK$(tput sgr0)"
 ERROR="$(tput setaf 1) ERROR$(tput sgr0)"
 
 GIT_PULL_HAD_ERROR="false"
+MVN_INSTALL_HAD_ERROR="false"
 
 REPOS=()
 REPOS+=("SlipStream")
@@ -67,7 +69,7 @@ update_ss_repo(){
   if [ -d ${1} ]
   then
     pecho "  - Updating ${1}... "
-    (cd ${1}; git_branch; if git pull; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || GIT_PULL_HAD_ERROR="true"; 
+    (cd ${1}; git_branch; if git pull; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || GIT_PULL_HAD_ERROR="true";
   else
     pecho "  - Repo ${1} is not yet cloned here. Cloning ${1}... "
     git clone git@github.com:slipstream/${1}.git && pecholn "$OK" || pecholn "$ERROR"
@@ -79,7 +81,7 @@ install_project(){
   if [ -d ${1} ]
   then
     pecho "  - Installing ${1}... "
-    (cd ${1}; git_branch; mvn install -Dmaven.test.skip=$SKIP_TESTS && pecholn "$OK" || pecholn "$ERROR")
+    (cd ${1}; git_branch; if mvn install -Dmaven.test.skip=$SKIP_TESTS; then pecholn "$OK"; else pecholn "$ERROR"; exit 1; fi;) || MVN_INSTALL_HAD_ERROR="true";
   else
     pecholn "  - Project ${1} not found. Skipping."
   fi
@@ -95,7 +97,7 @@ done
 
 if $GIT_PULL_HAD_ERROR
 then
-  pecholn 
+  pecholn
   pecholn "Some repos didn't update successfully. You might have uncommitted changes. Please fix it and re-run this command."
   exit 1
 fi
@@ -107,5 +109,21 @@ for repo in "${REPOS[@]}"
 do
   install_project $repo
 done
+
+if $MVN_INSTALL_HAD_ERROR
+then
+  pecholn
+  pecholn "Verify following common mistakes:"
+  pecholn "  - All maven versions must be consistent (including the SlipStreamUI project)"
+  pecholn "  - Use 'export LC_CTYPE=\"en_US.UTF-8\"' for pylint in project 'SlipStreamClient' (automatically done with this script)"
+  pecholn
+  pecholn "Try building the project with:"
+  pecholn "  (cd SlipStream; touch .slipstream-build-all; mvn clean install; rm .slipstream-build-all)"
+  pecholn "Source: https://github.com/slipstream/SlipStream/tree/master#build-everything"
+  pecholn
+  exit 1
+fi
+
+
 exit
 
